#if     !defined(__IOCTL_H__) 
#define __IOCTL_H__ 
 
#define IOCTL_READ_DISKIMAGE_FILE CTL_CODE(FILE_DEVICE_DISK, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS) 
 
#define IOCTL_WRITE_DISKIMAGE_FILE CTL_CODE(FILE_DEVICE_DISK,  0x910, METHOD_BUFFERED, FILE_ANY_ACCESS) 
 
#endif
